site_name: commonmeta-py
site_description: commonmeta-py PyPi Package Documentation
repo_url: https://github.com/front-matter/commonmeta-py/
edit_uri: ./edit/main/docs

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: index.md
  - Metadata: metadata.md
  - Readers: 
      - CFF: readers/cff_reader.ipynb
      - Crossref: readers/crossref_reader.ipynb
      - CrossrefXML: readers/crossref_xml_reader.ipynb
      - DataCite: readers/datacite_reader.ipynb
      - Schema.org: readers/schema_org_reader.ipynb
  - Writers:
      - BibTex: writers/bibtex_writer.ipynb
      - Citation: writers/citation_writer.ipynb
      - Citeproc: writers/citeproc_writer.ipynb
      - Commonmeta: writers/commonmeta_writer.ipynb
      - RIS: writers/ris_writer.ipynb

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - mkdocs-jupyter

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://front-matter.io
    - icon: fontawesome/brands/github
      link: https://github.com/front-matter/commonmeta-py
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/commonmeta-py/
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@mfenner
