project:
  type: website
  output-dir: _site
  preview:
    port: 4300
execute:
  freeze: true
website:
  title: "commonmeta-py"
  favicon: favicon.ico
  navbar:
    background: light
    logo: "/images/icon.png"
    logo-alt: "commonmeta-py"
    left:
      - href: index.qmd
        text: Guide
      - href: examples.qmd
        text: Examples
    tools:
      - icon: github
        href: https://github.com/front-matter/commonmeta-py
  page-footer:
    left: "Copyright &copy;2023 Front Matter."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://rogue-scholar.social/@admin

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    page-layout: article
    toc: true
    toc-location: left
